version: '3'
services:
  api:
    build: .
    image: 'codegov/code-gov-api:latest'
    container_name: 'code-gov-api'
    command: npm start
    ports:
      - "3000:3000/tcp"
    env_file:
      - .env
    depends_on:
      - elasticsearch
    working_dir: /usr/src/app/
    volumes:
      - .:/usr/src/app
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.9"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    container_name: 'code-gov-data'
